development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DEVELOPMENT_DB'] %>
  pool: 5
  username: <%= ENV['DEVELOPMENT_DB_USER'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['TEST_DB'] %>
  pool: 5
  username: <%= ENV['TEST_DB_USER'] %>
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PRODUCTION_DB'] %>
  pool: 5
  username: <%= ENV['PRODUCTION_DB_USER'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
